fields:
# include: include/header.twig
# sheet: Tales of the Old West Sheet
  # row
    # col: col-12
      # card: personal
        # card-body
          # row
            # col: col-4
            # /col
            # col: col-4
  image:
    label: "Tales of the Old West Sheet"
    url: /i/7786604/render    
    width: 300px
            # /col
            # col: col-4
            # /col
            # col: col-12 col-md-4
  Name:
    label: "Name"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-4
  Pardner:
    label: "Pardner"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-4
  portrait:
    label: "Portrait"
    input: integer
    render: image
    placeholder: "WA image ID"
            # /col
            # col: col-12 col-md-8
  Archetype:
    label: "Archetype"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-4
  Age:
    label: "Age"
    input: integer
            # /col
            # col: col-12 col-md-8
  Faith Text:
    label: "Faith"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-4
  # dots: 10
  Faith Points:
    label: "Faith Points"
    input: integer
    min: 0
    max: 10
            # /col
            # col: col-12 col-md-12
  Big Dream:
    label: "Big Dream"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-5
  Lifestyle:
    label: "Lifestyle"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-5
  Reputation:
    label: "Reputation"
    input: string
    placeholder: ""
            # /col
            # col: col-12 col-md-2
  # dots: 8
  Experience:
    label: "Experience"
    input: integer
    min: 0
    max: 8
            # /col
            # col: col-12 col-md-4
  Fame:
    label: "Fame"
    input: integer
            # /col
            # col: col-12 col-md-4
  Morals:
    label: "Morals"
    input: integer
            # /col
            # col: col-12 col-md-4
  Public Spirit:
    label: "Public Spirit"
    input: integer
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12 col-lg-12
      # card: attributes and skills
        # card-body
          # row
            # col: col-12 col-md-12 col-lg-12 hdr
  text:
    label: "Attributes and Skills"
            # /col
            # col: col-12 col-md-6 col-lg-3
  Grit:
    label: "Grit"
    input: integer
  Hurts:
    label: "Hurts Tracker"
    input: integer
              # table
  # width: 75%
  Fighting:
    label: "Fighting"
    input: integer
  Labor:
    label: "Labor"
    input: integer
  Presence:
    label: "Presence"
    input: integer
  Resilience:
    label: "Resilience"
    input: integer
              # /table
            # /col
            # col: col-12 col-md-6 col-lg-3
  Quick:
    label: "Quick"
    input: integer
  Shakes:
    label: "Shakes Tracker"
    input: integer
              # table
  # width: 75%
  Light-Fingered:
    label: "Light-Fingered"
    input: integer
  Move:
    label: "Move"
    input: integer
  Operate:
    label: "Operate"
    input: integer
  Shooting:
    label: "Shooting"
    input: integer
              # /table
            # /col
            # col: col-12 col-md-6 col-lg-3
  Cunning:
    label: "Cunning"
    input: integer
  Vexes:
    label: "Vexes Tracker"
    input: integer
              # table
  # width: 75%
  Animal Handling:
    label: "Animal Handling"
    input: integer
  Hawkeye:
    label: "Hawkeye"
    input: integer
  Insight:
    label: "Insight"
    input: integer
  Nature:
    label: "Nature"
    input: integer
              # /table
            # /col
            # col: col-12 col-md-6 col-lg-3
  Docity:
    label: "Docity"
    input: integer
  Doubts:
    label: "Doubts Tracker"
    input: integer
              # table
  # width: 75%
  Book Learning:
    label: "Book Learning"
    input: integer
  Doctoring:
    label: "Doctoring"
    input: integer
  Making:
    label: "Making"
    input: integer
  Performing:
    label: "Performing"
    input: integer
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: status
        # card-body
          # row
            # col: col-12 col-md-12 hdr
  text:
    label: "Status"
            # /col
            # col: col-12 col-md-12
  Critical Injuries:
    label: "Critical Injuries / Conditions"
    input: string
  Starving:
    label: "Starving"
    input: checkbox
  # nbsp:5
  Dehydrated:
    label: "Dehydrated"
    input: checkbox
  # nbsp:5
  Exhausted:
    label: "Exhausted"
    input: checkbox
  # nbsp:5
  Freezing:
    label: "Freezing"
    input: checkbox
  # nbsp:5
  Heatstroke:
    label: "Heatstroke"
    input: checkbox
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: talents
        # card-body
          # row
            # col: col-12 col-md-12 col-lg-12 hdr
  text:
    label: "Favored Weapons"
            # /col
            # col: col-12 col-md-12 col-lg-12
              # table: horiz
                # iter:1:10
  Weapon Type:
    label: "Type"
    input: string
  Weapon Qual:
    label: "Qualities/Cond."
    input: string
  Weapon Action:
    label: "Action"
    input: string
  Weapon Draw:
    label: "Draw"
    input: string
  Weapon Attack:
    label: "Attack"
    input: string
  Weapon Dam:
    label: "Dam"
    input: string
  Weapon Crit:
    label: "Crit"
    input: string
  Weapon Range:
    label: "Range"
    input: string
  Weapon Ammo:
    label: "Ammo"
    input: string
  Weapon Ammo Used:
    label: "Ammo used"
    input: string
                # /iter
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: talents
        # card-body
          # row
            # col: col-12 col-md-12 col-lg-12 hdr
  text:
    label: "Talents"
            # /col
            # col: col-12 col-md-12 col-lg-12
              # table: horiz
                # iter:1:10
  # width: 25%
  Talent Name:
    label: "Talent"
    input: string
  Talent Description:
    label: "Description"
    input: string
                # /iter
              # /table
            # /col
          # /row
        # /card-body
      # /card
    # /col
  # /row
  ### compadres
  # row
    # col: col-12 col-md-12
      # card: compadres
        # card-body
          # table
            # iter: 3
  Compadres Name:
    label: "Name"
    input: string
  Compadres Role:
    label: "Role"
    input: string
  Compadres Grit:
    label: "Grit"
    input: integer
  Compadres Quick:
    label: "Quick"
    input: integer
  Compadres Cunning:
    label: "Cunning"
    input: integer
  Compadres Docity:
    label: "Docity"
    input: integer
  Compadres Hurts:
    label: "Hurts"
    input: integer
  Compadres Shakes:
    label: "Shakes"
    input: integer
  Compadres Vexes:
    label: "Vexes"
    input: integer
  Compadres Doubts:
    label: "Doubts"
    input: integer
  Compadres Ability1 Name:
    label: "Ability1 Name"
    input: string
  Compadres Ability1 Value:
    label: "Ability1 Value"
    input: integer
  Compadres Ability2 Name:
    label: "Ability2 Name"
    input: string
  Compadres Ability2 Value:
    label: "Ability2 Value"
    input: integer
  Compadres Ability3 Name:
    label: "Ability3 Name"
    input: string
  Compadres Ability3 Value:
    label: "Ability3 Value"
    input: integer
  Compadres Notes:
    label: "Notes"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  ### remuda
  # row
    # col: col-12 col-md-12
      # card: remuda
        # card-body
          # table
            # iter: 3
  Remuda Name:
    label: "Name"
    input: string
  Remuda Breed:
    label: "Breed"
    input: string
  Remuda Riding Bonus:
    label: "Riding Bonus"
    input: string
  Remuda Qualities:
    label: "Qualities"
    input: string
  Remuda Flaws:
    label: "Flaws"
    input: string
  Remuda Grit:
    label: "Grit"
    input: integer
  Remuda Quick:
    label: "Quick"
    input: integer
  Remuda Cunning:
    label: "Cunning"
    input: integer
  Remuda Resilience:
    label: "Resilience"
    input: integer
  Remuda Move:
    label: "Move"
    input: integer
  Remuda Fighting:
    label: "Fighting"
    input: integer
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  ### horse
  # row
    # col: col-12 col-md-12
      # card: horse
        # card-body
          # table
  Horse Name:
    label: "Name"
    input: string
  Horse Breed:
    label: "Breed"
    input: string
  Horse Riding Bonus:
    label: "Riding Bonus"
    input: string
  Horse Qualities:
    label: "Qualities"
    input: string
  Horse Flaws:
    label: "Flaws"
    input: string
  Horse Grit:
    label: "Grit"
    input: integer
  Horse Quick:
    label: "Quick"
    input: integer
  Horse Cunning:
    label: "Cunning"
    input: integer
  Horse Hurts:
    label: "Hurts"
    input: integer
  Horse Shakes:
    label: "Shakes"
    input: integer
  Horse Vexes:
    label: "Vexes"
    input: integer
  Horse Resilience:
    label: "Resilience"
    input: integer
  Horse Move:
    label: "Move"
    input: integer
  Horse Fighting:
    label: "Fighting"
    input: integer
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: gear
        # card-body
          # row
            # col: col-12 col-md-12 hdr
  text:
    label: "Gear"
            # /col
            # col: col-6 col-md-6
  Cash:
    label: "Cash"
    input: string
            # /col
            # col: col-6 col-md-6
  Capital:
    label: "Capital"
    input: string
            # /col
            # col: col-12 col-md-12
  Gear:
    input: text
    rows: 4
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: notes
        # card-body
  Background:
    label: "Background"
    input: text
    rows: 4
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: notes
        # card-body
  Notes:
    label: "Notes"
    input: text
    rows: 4
        # /card-body
      # /card
    # /col
  # /row
  # br
  # hr
  # br
  # include: include/footer.twig
# /sheet