type: map
mapping:
  version:
    type: str
    required: true
  system:
    type: str
    required: true
  author:
    type: map
    required: true
    mapping:
      username:
        type: str
        required: true
      email:
        type: str
        required: true
        pattern: .+@.+
  unique_reference:
    type: str
    required: true
  table:
    type: bool
    required: false
  name:
    type: str
    required: true
  display_template:
    type: str
    required: true
    pattern: .+.html.twig
  description:
    type: str
    required: true
  instructions:
    type: str
    required: true
  fields:
    type: map
    required: true
    mapping:
      name:
        type: map
        required: true
        mapping:
          input:
            type: str
            required: true
          description:
            type: str
            required: true
          label:
            type: str
            required: true
          placeholder:
            type: str
            required: false
          required:
            type: bool
            required: false